# Copyright Red Hat
# Run `make samples` if you modified the orginal file located in the project resources directory
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterregistrar-role
rules:
# Setting this first rule as a convenience for installing the APIResourceSchema and APIExports
# using service account kubeconfig file on hand via Makefile
- apiGroups: ["apis.kcp.dev"]
  resources: ["apiresourceschemas", "apiexports"]
  verbs: ["create", "update", "patch", "get", "list"]
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/content
  resourceNames:
  - compute-apis
  - compute-apis/status
  - compute-apis/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
  - patch
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - singapore.open-cluster-management.io
  resources:
  - registeredclusters
  - registeredclusters/status
  - registeredclusters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
  - patch
