# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .KcpSyncerName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .KcpSyncerName }}
subjects:
- kind: ServiceAccount
  name: {{ .ServiceAccountName }}
  namespace: default
