# Copyright Red Hat
# Run `make samples` if you modified the orginal file located in the project resources directory
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: compute-apis
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: serviceaccounts
  # - group: "rbac.authorization.k8s.io"
  #   resource: clusterroles
  # - group: "rbac.authorization.k8s.io"
  #   resource: clusterrolebindings
  latestResourceSchemas:
  - latest.registeredclusters.singapore.open-cluster-management.io
