apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        compute-antiaffinity-selector: compute-installer-controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: compute-antiaffinity-selector
                      operator: In
                      values:
                        - compute-installer-controller
                topologyKey: topology.kubernetes.io/zone
              weight: 70
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: compute-antiaffinity-selector
                      operator: In
                      values:
                        - compute-installer-controller
                topologyKey: kubernetes.io/hostname
              weight: 35
      containers:
      - args:
        - installer
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTROLLER_IMAGE
          valueFrom:
            configMapKeyRef:
              name: installer-config
              key: IMAGE
        - name: SKIP_WEBHOOK
          valueFrom:
            configMapKeyRef:
              name: installer-config
              key: SKIP_WEBHOOK
        image: controller:latest
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        name: installer
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 150Mi
      serviceAccountName: compute-installer-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
        - key: dedicated
          operator: Exists
          effect: NoSchedule
